---
- name: " Installing Prometheus"
  hosts: amazon
  become: true
  vars:
    ip: "node-exporter ip"
  tasks:


  - name: " Installing Prometheus"
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v2.32.1/prometheus-2.32.1.linux-amd64.tar.gz"
      dest: "/opt/"
      remote_src: true

  - name: "Copying the files"
    copy:
      src: "/opt/prometheus-2.32.1.linux-amd64/prometheus"
      dest: "/usr/local/bin/prometheus"  
      remote_src: true
      owner: root
      group: root
      mode: 0755


  - name: "Copying config file"
    template:
      src: "prometheus.config.tmp"
      dest: "/opt/prometheus-2.32.1.linux-amd64/prometheus.yml"
      owner: root
      group: root

  - name: "Creating systemd service for node-exporter"
    template:
      src: "prometheus.service.tmp"
      dest: "/etc/systemd/system/prometheus.service"
      owner: root
      group: root
      mode: 0600


  - name: "configure systemd"
    systemd:
      daemon_reload: true
      enabled: true
      state: started
      name: prometheus.service
